version: "3.8"

services:
  agent_service:
    build:
      context: ./agent_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./agent_service/.env
    networks:
      - app_network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    env_file: ./auth_service/.env
    networks:
      - app_network

  nginx:
    image: nginx:1.29-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth_service
      - agent_service
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
