
services:
  agent_service:
    build:
      context: ./agent_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./agent_service/.env

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    env_file: ./auth_service/.env